// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecommendUIClient is the client API for RecommendUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendUIClient interface {
	// ListEngineSpecs returns a list of Recommend Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RecommendUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type recommendUIClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendUIClient(cc grpc.ClientConnInterface) RecommendUIClient {
	return &recommendUIClient{cc}
}

func (c *recommendUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RecommendUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RecommendUI_ServiceDesc.Streams[0], "/v1.RecommendUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &recommendUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecommendUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type recommendUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *recommendUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recommendUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.RecommendUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendUIServer is the server API for RecommendUI service.
// All implementations must embed UnimplementedRecommendUIServer
// for forward compatibility
type RecommendUIServer interface {
	// ListEngineSpecs returns a list of Recommend Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, RecommendUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedRecommendUIServer()
}

// UnimplementedRecommendUIServer must be embedded to have forward compatible implementations.
type UnimplementedRecommendUIServer struct {
}

func (UnimplementedRecommendUIServer) ListEngineSpecs(*ListEngineSpecsRequest, RecommendUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedRecommendUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedRecommendUIServer) mustEmbedUnimplementedRecommendUIServer() {}

// UnsafeRecommendUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendUIServer will
// result in compilation errors.
type UnsafeRecommendUIServer interface {
	mustEmbedUnimplementedRecommendUIServer()
}

func RegisterRecommendUIServer(s grpc.ServiceRegistrar, srv RecommendUIServer) {
	s.RegisterService(&RecommendUI_ServiceDesc, srv)
}

func _RecommendUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommendUIServer).ListEngineSpecs(m, &recommendUIListEngineSpecsServer{stream})
}

type RecommendUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type recommendUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *recommendUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RecommendUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RecommendUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendUI_ServiceDesc is the grpc.ServiceDesc for RecommendUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RecommendUI",
	HandlerType: (*RecommendUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _RecommendUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _RecommendUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recommend-ui.proto",
}
